---
apiVersion: v1
kind: ImageStream
metadata:
  name: angular-centos-s2i
  creationTimestamp: null
  annotations:
    openshift.io/display-name: Angular
spec:
  tags:
    - name: latest
      annotations:
        openshift.io/display-name: Angular
        description: >-
          Build and run Angular 8+ apps based on the official
          centos/httpd-24-centos7 image. For more information about using this
          builder image, see https://github.com/mprahl/s2i-angular-httpd24.
        iconClass: icon-js
        tags: 'builder,angular,javascript' 
        supports: 'angular' 
      from:
        kind: DockerImage
        name: 'theturingnerd/angular-centos-s2i:latest'
